### ISSUE TITLE
Redis cluster Migrator not working

### ISSUE THREAD

**Issue by noonenene** [redis/redis-om-python#408]
```py
from redis.cluster import RedisCluster as Redis
redis_userdb = Redis(host='xxx.yyy.zzz.xx', port=xxxx, password='password)
print(redis_userdb.get_nodes())
```

I able to write data on all cluster node without any issue but not able to run `Migrator().run()`

```py
print(Users.get("user1"))
Migrator().run()
```

```py
ResponseError: Unknown Index name
Traceback (most recent call last):
  File "/home/ubuntu/project/.venv/lib/python3.8/site-packages/redis/cluster.py", line 1074, in _execute_command
    response = redis_node.parse_response(connection, command, **kwargs)
  File "/home/ubuntu/project/.venv/lib/python3.8/site-packages/redis/client.py", line 1254, in parse_response
    response = connection.read_response()
  File "/home/ubuntu/project/.venv/lib/python3.8/site-packages/redis/connection.py", line 839, in read_response
    raise response
redis.exceptions.ResponseError: Unknown Index name
MovedError
Traceback (most recent call last):
  File "/home/ubuntu/project/.venv/lib/python3.8/site-packages/redis/cluster.py", line 1074, in _execute_command
    response = redis_node.parse_response(connection, command, **kwargs)
  File "/home/ubuntu/project/.venv/lib/python3.8/site-packages/redis/client.py", line 1254, in parse_response
    response = connection.read_response()
  File "/home/ubuntu/project/.venv/lib/python3.8/site-packages/redis/connection.py", line 839, in read_response
    raise response
redis.exceptions.MovedError: 13099
```

**Comment by msarm** [comment]
In the [Version 0.1.0](https://github.com/redis/redis-om-python/releases/tag/v0.1.0), the below change was made and causing this issue. 
<img width="1643" alt="image" src="https://user-images.githubusercontent.com/1042633/203859538-b3787f89-b0c5-4017-bb7d-1d8f4c3d10da.png">
